language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: npm run build
deploy:

  provider: pages
  skip-cleanup: true
  github-token: $token
  on:
    branch: travis
notifications:
  email: false
